# Form implementation generated from reading ui file 'Window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Main_window(object):
    def setupUi(self, Main_window):
        Main_window.setObjectName("Main_window")
        Main_window.resize(660, 83)
        Main_window.setMinimumSize(QtCore.QSize(660, 83))
        Main_window.setMaximumSize(QtCore.QSize(660, 83))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("download24.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Main_window.setWindowIcon(icon)
        self.btn_exit = QtWidgets.QPushButton(parent=Main_window)
        self.btn_exit.setGeometry(QtCore.QRect(570, 50, 75, 24))
        self.btn_exit.setObjectName("btn_exit")
        self.btn_start_mp4 = QtWidgets.QPushButton(parent=Main_window)
        self.btn_start_mp4.setGeometry(QtCore.QRect(470, 50, 91, 24))
        self.btn_start_mp4.setObjectName("btn_start_mp4")
        self.input_url = QtWidgets.QLineEdit(parent=Main_window)
        self.input_url.setGeometry(QtCore.QRect(120, 10, 521, 21))
        self.input_url.setObjectName("input_url")
        self.lbl_url = QtWidgets.QLabel(parent=Main_window)
        self.lbl_url.setGeometry(QtCore.QRect(10, 10, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_url.setFont(font)
        self.lbl_url.setObjectName("lbl_url")
        self.btn_start_mp3 = QtWidgets.QPushButton(parent=Main_window)
        self.btn_start_mp3.setGeometry(QtCore.QRect(370, 50, 91, 24))
        self.btn_start_mp3.setObjectName("btn_start_mp3")
        self.progressBar = QtWidgets.QProgressBar(parent=Main_window)
        self.progressBar.setGeometry(QtCore.QRect(10, 50, 211, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")

        self.retranslateUi(Main_window)
        QtCore.QMetaObject.connectSlotsByName(Main_window)

    def retranslateUi(self, Main_window):
        _translate = QtCore.QCoreApplication.translate
        Main_window.setWindowTitle(_translate("Main_window", "Youtube MP3 Downloader"))
        self.btn_exit.setText(_translate("Main_window", "Exit"))
        self.btn_start_mp4.setText(_translate("Main_window", "Start als MP4"))
        self.lbl_url.setText(_translate("Main_window", "URL Eingeben:"))
        self.btn_start_mp3.setText(_translate("Main_window", "Start als MP3"))
